version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Run SonarQube Scan
          command: |
            export SONAR_TOKEN=${SONAR_TOKEN}
            export SONAR_HOST_URL="https://sonarcloud.io"
            ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
